### ISSUE TITLE
Unable to use custom Nominatim API in subdirectory

### ISSUE THREAD

**Issue by JulianPaulus** [joaquimserafim/node-open-geocoder#3]
It's impossible to use a custom Nominatim when it's in a subdirectory due to the port, even if default, being added to the end of the url.
`Error: getaddrinfo ENOTFOUND http://<domain>.com/nominatim/ http://<domain>.com/nominatim/:80`

**Comment by joaquimserafim** [comment]
Hi can you give-me an example please, many thanks

**Comment by JulianPaulus** [comment]
Well, I have no way, at least how I see it, that enables me to use a url with a path since the constructor only accepts a hostname to which the port is automatically attached. Which means that if I pass it a path with the hostname it ends up like `http://<hostname>/<path>:80` instead of `http://<hostname>:80/<path>` which ends up throwing the error that you can see in my first post.

**Comment by JulianPaulus** [comment]
Something like this should work out.
```javascript
// In the constructor
this.httpOptions = {
      hostname: getPropValue(options, 'url') || 'nominatim.openstreetmap.org',
      // Add a basePath option
      basePath: getPropValue(options, 'basePath') || '',
      port: getPropValue(options, 'port') || 80,
      agent: false
    }


// In the end method
end (cb) {
    // Instead of passing the Options object as a whole, split it up and send it as a String
    const req = http.get(this.httpOptions.hostname + ':' + this.httpOptions.port + this.httpOptions.basePath + this.httpOptions.path, responseHandler.bind(this, cb))
    ...
```
I haven't yet tested if this works but I'd really appreciate if you could have a look at it.
I'll see if I can create a pull request once I'm at home.

**Comment by joaquimserafim** [comment]
if you could do that I appreciate it 👍 thanks

**Comment by joaquimserafim** [comment]
merged :) many thanks mate and take care.
