### ISSUE TITLE
Error: Request Failed.

### ISSUE THREAD

**Issue by xeroxstar** [joaquimserafim/node-open-geocoder#8]
Hello,
I am trying to geocode this city but getting an error:

`openGeocoder().geocode('Montréal, Québec, Canada').end(async (error, data) => {`
          

> console.log(error) //Error: Request Failed.

`})`

**Comment by xeroxstar** [comment]
Fixed it with the `npm install latinize` , it convert accented characters to a string. 

```
const latinize = require('latinize');
openGeocoder().geocode(latinize ('Montréal, Québec, Canada')).end(async (error, data) => {

console.log(error) //Error: Request Failed.

})
```

**Comment by joaquimserafim** [comment]
No worries mate, but I fixed with `v4` 

Thanks
